### ISSUE TITLE
Allow sidebar to define pagination order and progress

### ISSUE THREAD

**Issue by shawntabrizi** [imyelo/docsify-pagination#12]
Right now, if you structure your docsify page to have main sections, and sub sections, pagination starting at a main section will take you between main sections, and sub sections will keep you only within the main section parent

```
- Section 1                        Pagination takes you to Section 2
|
---- Sub-Section 1.1.        Pagination takes you to Subsection 1.2
|
---- Sub-Section 1.2.       Pagination takes you to Subsection 1.3
|
---- Sub-Section 1.3.       End of Pagination
|
- Section 2.                      Pagination takes you to Section 3
|
---- Sub-Section 2.1.      Pagination takes you to Subsection 2.2
|
---- Sub-Section 2.2.     End of Pagination
|
- Section 3
|
...
```

Whereas I would want to set it up so that:
Section 1 -> Subsection 1.1 -> Subsection 1.2 -> Subsection 1.3 -> Section 2 -> etc...

**Comment by cyrilf** [comment]
I totally agree with you on this behavior.
As I don't want to break the current behavior I created a new PR #14 with an extra option `crossChapter` to allow going from a chapter to the previous/next one.
We'll see if it get accepted. :v:

**Comment by shawntabrizi** [comment]
Nice @cyrilf, will be really happy to use this in my project when it is made available on a cdn (or I guess I can just copy your pr locally)

**Comment by imyelo** [comment]
Agree with you, and it's just other tasks always on the top of my list.
#14 is helping. Thank @cyrilf again and closing this issue. Please feel free to reopen if you still have any problems.
