### ISSUE TITLE
Pagination open new page on end. Open pagination on top of page

### ISSUE THREAD

**Issue by marcelomrwin** [imyelo/docsify-pagination#13]
When we use paging function the new page opens with bottom focus. Like a book it's possible to open the new page with focus on top of page?

**Comment by imyelo** [comment]
Makes sense, but it seems like docsify itself has done this for us.

https://github.com/docsifyjs/docsify/blob/d5910bd/src/core/render/index.js#L124

**Comment by marcelomrwin** [comment]
Yes @imyelo , That is it. Thanks. 
Just put: 

> `auto2top: true`

 in your configuration and everything works fine.
