### ISSUE TITLE
Version 2.4.0 is not working

### ISSUE THREAD

**Issue by safris** [imyelo/docsify-pagination#15]
When I cloned the repo and ran the example, the pagination links are missing. If I replace
```
<script src="../dist/docsify-pagination.js"></script>
```
with
```
<script src="//unpkg.com/docsify-pagination@2.3.5/dist/docsify-pagination.js"></script>
```
the links are present.

**Comment by imyelo** [comment]
Hmmm, the `dist` directory is generated with `npm run build` and will not be pushed into the git repository. So the cloned example cannot find our script in this case (unless we execute `npm run build`). 

That is a bit confusing. 🤔 Maybe I should write a script for running example, something like `npm run example` and build `dist` directory inside first.

**Comment by imyelo** [comment]
> Hmmm, the `dist` directory is generated with `npm run build` and will not be pushed into the git repository. So the cloned example cannot find our script in this case (unless we execute `npm run build`).
> 
> That is a bit confusing. 🤔 Maybe I should write a script for running example, something like `npm run example` and build `dist` directory inside first.

`yarn example` Added.

https://github.com/imyelo/docsify-pagination#how-to-open-these
