### ISSUE TITLE
pagination seems to be erased by Docsify's Vue handling?

### ISSUE THREAD

**Issue by trusktr** [imyelo/docsify-pagination#16]
Whenever I stick a Vue component in my markdown, it erases the pagination.

It seems like it may be related to this Docsify code: 

https://github.com/docsifyjs/docsify/blob/develop/src/core/render/index.js#L57-L61

Maybe the pagination is rendered into `#main` before the Vue instance is rendered onto `#main`?

I can reproduce it by using the `vuep` component that [Docsify recommends](https://docsify.js.org/#/vue?id=combine-vuep-to-write-playground). When I instantiate a code editor view, like

```vue
<vuep .../>
<script>
  // ... CONTENT FOR THE EDITOR ...
</script>
```

it causes the pagination to disappear for that page.

**Comment by trusktr** [comment]
Okay, this is weird. I noticed something: If I have any content before the `vuep` component, then it appears in the output. Anything after the vuep code editor does not appear.

For example, if I have

```md
this content appears fine

<vuep ...>
<script>
  // 
</script>

this content disappears
```

then what happens is that `this content appears fine` shows up before the editor, but `this content disappears` never appears in the output.

So, because pagination appears after the editor, it doesn't get rendered for some reason.

@QingWei-Li @timaschew Any ideas?

**Comment by trusktr** [comment]
I can work around the issue by using a different approach to load Vuep, in my markdown:

```html
this content appears fine

<div id="hello3d"></div>
<script type="application/javascript">
  new Vue({
    el: '#hello3d',
    template: `
      <vuep ... />
    `,
    data: {
      code: `
  // ... same code that was inside the script tag of previous example ...
`
    }
  })
</script>

this content appears fine
```

Now with this approach, both content before and after appear in the output.

**Comment by imyelo** [comment]
This is weird. Seems like vuep don't work well with docsify's hooks.

**Comment by trusktr** [comment]
Closing this as Docsify's Vue support has been totally re-worked, totally different implementation now.
