### ISSUE TITLE
Please set a config for handling different attributes

### ISSUE THREAD

**Issue by mrpotatoes** [imyelo/docsify-pagination#18]
So, for example, In my pagination if I click "Fantasy Land" it'll go out to that link. I would prefer if I could set an option to not follow the link.

* Example: [Follows link](https://mrpotatoes.github.io/functional-programming-in-js-reference/#/misc/credits-and-contributors
)
* [Link attributes in `Docsify`](https://docsify.js.org/#/helpers?id=set-target-attribute-for-link)

**Comment by imyelo** [comment]
I tend to avoid adding options as much as possible, which sometimes complicates the configuration.
Just for this use case, I think this just-merged PR #34 might be just the ticket. It will keep the link behaviour in pagination consistent with the one in the sidebar (currently, only External is supported).
Please free feel to reopen if I misunderstood.
