### ISSUE TITLE
When the sidebar is hidden, the next and previous pages are not shown

### ISSUE THREAD

**Issue by mafanwei** [imyelo/docsify-pagination#21]
This is a problem that can easily recur, for example：
```
window.$docsify = {
      name: '',
      repo: '',
      loadSidebar: true,
      hideSidebar: true,
      loadNavbar: true,
      pagination: {
        previousText: '上一页',
        nextText: '下一页',
        crossChapter: true,
        crossChapterText: true,
      },
    }
```

**Comment by imyelo** [comment]
I'm afraid I can do nothing at this moment. Docsify-pagination depends on the DOM tree for collecting sidebar information. Option 'hideSidebar' would remove the sidebar element from DOM, which is precisely what we can do nothing without.
