### ISSUE TITLE
Fail to redirect when the pagination links to external domain & Docsify is on `history` router mode

### ISSUE THREAD

**Issue by rizdaprasetya** [imyelo/docsify-pagination#24]
#### When:
- i'm using `routerMode: 'history',` 
```javascript
    window.$docsify = {
      routerMode: 'history',
    }
```
- AND the sidebar contains external domain link
```markdown
- [Home](/)
- [External Site Link](https://example.org)
```

#### Then:
- I click the pagination to that external domain link (see attached image at bottom)

#### Actual:
- The redirect fails, with JS console error
```javascript
Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'https://example.org/' cannot be created in a document with origin 'https://mighty-jazzy-comte.glitch.me' and URL 'https://mighty-jazzy-comte.glitch.me/second-page'.
    at https://unpkg.com/docsify/lib/docsify.min.js:1:97812
```

#### Expected:
- I should be redirected to the link just fine

#### Possibility
It fails because the Docsify `routerMode` is `history`, and Docsify requires any external links to have `target="_blank"` attributes, in order to count the link as external (cross domain) link. Probably will need special handling around here:
https://github.com/imyelo/docsify-pagination/blob/47c8dd71fd76e0bd630e5854ae8adedbd74a6152/src/pagination.js#L102

## Live Demo
Visit this demo site and follow the guide to reproduce the bug:
- https://mighty-jazzy-comte.glitch.me

To inspect the source code plase visit:
- https://glitch.com/edit/#!/mighty-jazzy-comte

## Sample
> <img width="920" alt="Screen Shot 2021-02-09 at 14 47 43" src="https://user-images.githubusercontent.com/13027142/107331966-21fa3480-6ae6-11eb-8602-6bc0e3edfdc6.png">

Anyway great and useful plugin, kudos for making this plugin happen in the first place 🎉

**Comment by imyelo** [comment]
Fixed with #34 and [v2.10.0](https://github.com/imyelo/docsify-pagination/releases/tag/v2.10.0) released. Thanks for contributing such detailed information 😘
