### ISSUE TITLE
No pagination on main landing page.

### ISSUE THREAD

**Issue by userdocs** [imyelo/docsify-pagination#25]
First, thanks for the plugin, it works except for one issue I cannot resolve using github pages.

When visiting the top level URL https://userdocs.github.io/qbittorrent-nox-static pagination does not load.

![image](https://user-images.githubusercontent.com/16525024/117549020-098bae80-b030-11eb-9890-a4706d33755b.png)

No configuration option I have found can solve this to add `/#/README` to initial loading of the page.

If I visit this URL instead, it works.

https://userdocs.github.io/qbittorrent-nox-static/#/README

![image](https://user-images.githubusercontent.com/16525024/117549340-c9c5c680-b031-11eb-978b-24284335d4a1.png)

I was wondering if I had missed a configuring combination or if that is just a limitation of docsify?

The html is here https://raw.githubusercontent.com/userdocs/qbittorrent-nox-static/master/docs/index.html

Any help you can provide would be appreciated.

**Comment by imyelo** [comment]
This is a limitation. Maybe we can add a default value for [`path`](https://github.com/imyelo/docsify-pagination/blob/7abdf8e/src/pagination.js#L68) in this case. PR Welcome

**Comment by chriskoelle** [comment]
@userdocs I ran into this same issue. A fix that worked for me was to change the link of the first item in my sidebar to `/`

for example change:
```md
-  [Home](README.md)
```
to
```md
-  [Home](/)
```
The `/` path should still load the README file since it's set as the homepage in your docsify options, and the pagination will be able to match the `/` path.

**Comment by userdocs** [comment]
It does work for the `/` but you lose it on `/README`  so it's solves half the problem.

but this looks like the fix for both https://github.com/imyelo/docsify-pagination/pull/29 so thanks @ruanqizhen

**Comment by imyelo** [comment]
Reviewing this again after a long time, it seems that using a unified path for a page is the better way to go into this scenario, which is also more in line with the convention in Doscify of implicitly pointing '/' to 'README.md'.
But as a plugin, we can indeed make some compatibility strategies for it. So #32 opened, and I hope it helps.
