### ISSUE TITLE
correct links on desktop, but incorrect links on mobile.

### ISSUE THREAD

**Issue by trusktr** [imyelo/docsify-pagination#27]
This is an interesting one: on desktop, the previous and next links go to the correct sections as expected.

On a mobile phone (Android Chrome) or even in Chrome mobile emulator, the links point to items in my nav bar (which is merged into the sidebar with Docsify's [`mergeNavbar` option](https://docsify.js.org/#/configuration?id=mergenavbar) set to true).

Here's the page to test:

https://lume.io/docs/#/examples/hello-world/

I _think_ it might happen when `mergeNavbar` is true. Seems that docsify-pagination is picking up the navbar links.

**Comment by trusktr** [comment]
Here are screenshots:

<img src="https://user-images.githubusercontent.com/297678/121073577-8755ed80-c787-11eb-8609-7fe91b02f072.png" width="400" />

![correct](https://user-images.githubusercontent.com/297678/121073580-87ee8400-c787-11eb-8e71-c73f5f77f50a.png)

**Comment by hqshi** [comment]
> This is an interesting one: on desktop, the previous and next links go to the correct sections as expected.
> 
> On a mobile phone (Android Chrome) or even in Chrome mobile emulator, the links point to items in my nav bar (which is merged into the sidebar with Docsify's [`mergeNavbar` option](https://docsify.js.org/#/configuration?id=mergenavbar) set to true).
> 
> Here's the page to test:
> 
> https://lume.io/docs/#/examples/hello-world/
> 
> I _think_ it might happen when `mergeNavbar` is true. Seems that docsify-pagination is picking up the navbar links.

In order to solve ploblem, you can download a copy and  change the css select from '.sidebar li a' to '.sidebar-nav li a'

just like what #28

**Comment by imyelo** [comment]
fixed with #28 in v2.6.2. Thanks to @hqshi !
