### ISSUE TITLE
Does not scroll to the top of the page when clicking a pagination link

### ISSUE THREAD

**Issue by stuft2** [imyelo/docsify-pagination#37]
Great plugin BTW!

## Steps to reproduce:
1. Create two pages in the same collection
2. Add text to both of them to make them long and require scrolling to see the bottom
3. Scroll to the bottom of the first page and click the next button
4. It should jump you to the top of the next page but instead I see I'm still at the bottom of the next page. Same problem clicking the previous page link as well.

**Comment by smit245** [comment]
you should use `auto2top: true` in your configuration.
it will fix your problem
